"""add user_id to tasks

Revision ID: 94f026b3ae60
Revises: 
Create Date: 2026-03-25 13:44:21.479365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94f026b3ae60'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_task', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_task', 'user_table', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_task', type_='foreignkey')
    op.drop_column('user_task', 'user_id')
    # ### end Alembic commands ###
